### ISSUE TITLE
Better Rolls card for rolls which remain standard rolls

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#222]
- [ ] Pace rolls as in #115.
- [ ] Wealth rolls as in #181.
- [ ] Arcane Device rolls as in #343 

Anything I have missed?
